<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CapacitorTestPlatform.Services</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CapacitorTestPlatform.Core\CapacitorTestPlatform.Core.csproj" />
    <ProjectReference Include="..\CapacitorTestPlatform.Data\CapacitorTestPlatform.Data.csproj" />
  </ItemGroup>

</Project>
